webscraping/
    __init__.py
    scheduler.py
    scrapeBelgianHappiness.py
    scrapeBiab.py
    scrapeEtre.py
    scrape_knl.py
    scraper.py
    scraperSchedule.py
    slackReceiver.py
    spiders/
        __init__.py
        belgianHappinessSpider.py
        biabSpider.py
        cantillionSpider.py
        etreSpider.py
        knl_spiders.py
    tests/
        __init__.py
        test_schedule.py
        test_compare_tools.py
    utils/
        __init__.py
        compare_tools.py
        getRandomUserAgent.py
        slackTools.py
        slack_tools.py