webscraping/
    __init__.py
    scheduler.py
    scrapeBelgianHappiness.py
    scrapeBiab.py
    scrapeEtre.py
    scrape_knl.py
    scraper.py
    scraperSchedule.py
    slackReceiver.py
    spiders/
        __init__.py
        belgianHappinessSpider.py
        biabSpider.py
        cantillionSpider.py
        etreSpider.py
        knl_spider.py
    tests/
        __init__.py
        testScraperSchedule.py
    utils/
        __init__.py
        compareInventories.py
        getRandomUserAgent.py
        slackTools.py