webscraper/
	__init__.py
	scrapeBelgianHappiness.py
	scrapeBiab.py
	scrapeEtre.py
	scrapeKnl.py
	scraper.py
	slackReceiver.py
	spiders/
		__init__.py
		belgianHappinessSpider.py
		biabSpider.py
		cantillionSpider.py
		etreSpider.py
		knlSpider.py
	utils/
		__init__.py
		compareInventories.py
		getRandomUserAgent.py 
		slackTools.py